const { withAppBuildGradle } = require('expo/config-plugins');

// Fixes CMake 250-char/Windows MAX_PATH issues on Windows.
// Redirects CMake build staging from the deep default path:
//   C:\repo\engineering-daybook\mobile\android\app\.cxx\...  (~184+ chars)
// to a short path:
//   C:\t\cxx\...  (~10 chars)
//
// Gradle merges multiple android { } blocks, so appending a separate block
// is safe and does not interfere with the block generated by expo prebuild.
module.exports = function withShortCxxPath(config) {
  // This fix is Windows-only: it shortens the CMake staging directory to work
  // around Windows MAX_PATH (260-char) limits. On macOS/Linux (including EAS cloud
  // builders), the C:/t/cxx path is meaningless and would create a stray `C:` dir.
  if (process.platform !== 'win32') {
    return config;
  }

  return withAppBuildGradle(config, (config) => {
    const buildGradle = config.modResults.contents;

    const marker = '// [withShortCxxPath]';
    if (buildGradle.includes(marker)) {
      return config; // idempotent — already applied
    }

    config.modResults.contents =
      buildGradle +
      `
${marker}
android {
    externalNativeBuild {
        cmake {
            buildStagingDirectory "C:/t/cxx"
        }
    }
}
`;
    return config;
  });
};
